openapi: 3.0.0
info:
  title: Event API
  version: '1.0'
  description: Event management API
  contact:
    name: Clivens Petit
    url: 'https://www.linkedin.com/in/peclevens'
    email: clivens.petit@magicsoftbay.com
  license:
    name: GNU GPLv3
    url: 'https://github.com/peclevens/event-apis-specs/blob/master/LICENSE'
servers:
  #- url: 'http://{environment}.events.clivenspetit.com:{port}/{basePath}'
  - url: 'http://{environment}.events.clivenspetit.com:{port}'
    description: API server
    variables:
      environment:
        enum:
          - test
          - dev
          - qa
          - prod
        default: dev
        description: API running environment
      port:
        enum:
          - '8443'
          - '443'
        default: '8443'
      basePath:
        default: v1
paths:
  /events:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/event.v1.json
      operationId: getAllEvents
      tags: []
      summary: List all event
      description: List all event
    post:
      responses:
        '201':
          description: Event created
          content:
            application/json:
              schema:
                $ref: ./models/id.v1.json
      tags: []
      operationId: createEvent
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/createevent.v1.json
        description: Event creation request
      summary: Create new event
      description: Create new event
    delete:
      responses:
        '204':
          description: No Content
      operationId: deleteAllEvent
      tags: []
      summary: Delete all events
      description: Delete all events
    parameters: []
  '/events/{id}':
    parameters:
      - name: id
        in: path
        schema:
          type: string
        description: Event id
        required: true
    get:
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/event.v1.json
      operationId: getEventById
      summary: Get event by id
      description: Get event by id
    delete:
      responses:
        '204':
          description: No Content
      tags: []
      operationId: deleteEventById
      summary: Delete event by id
      description: Delete event by id
    put:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/event.v1.json
      operationId: updateEventById
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/event.v1.json
      summary: Update event
      description: Update event
  '/events/{id}/sessions':
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: Event id
    get:
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/session.v1.json
      operationId: getSessionsByEventId
      summary: Get all sessions for a particular event
      description: Get all sessions for a particular event
    delete:
      responses:
        '204':
          description: No Content
      operationId: deleteAllSessionsByEventId
      tags: []
      summary: Delete all sessions for a particular event
      description: Delete all sessions for a particular event
    post:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/id.v1.json
      tags: []
      operationId: createSession
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/createsession.v1.json
      summary: Create a session for a particular event
      description: Create a session for a particular event
  '/events/sessions/{id}':
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: Session id
    get:
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/session.v1.json
      operationId: getSessionById
      summary: Get session by id
      description: Get session by id
    put:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/session.v1.json
      operationId: updateSessionById
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/session.v1.json
      summary: Update a session
      description: Update a session
    delete:
      responses:
        '204':
          description: No Content
      operationId: deleteSessionById
      tags: []
      summary: Delete session by id
      description: Delete session by id
